const images = {
    BG_IMAGE: require('../../assets/images/splash_bg.png'),
    APP_ICON: require('../../assets/images/app_icon.png'),
    ERROR_ICON: require('../../assets/images/error_icon.png'),
    CHECKED_ICON: require('../../assets/images/checked_icon.png'),
    OR_BG: require('../../assets/images/or_bg.png'),
    ONBOARD_BG: require('../../assets/images/onboard_bg.png'),
    GOOGLE_ICON: require('../../assets/images/google_icon.png'),
    FACEBOOK_ICON: require('../../assets/images/facebook_icon.png'),
    HIDE_ICON: require('../../assets/images/hide_icon.png'),
    SHOW_ICON: require('../../assets/images/show_icon.png'),
    LEFTARROW_ICON: require('../../assets/images/leftArrow_icon.png'),
    RIGHTARROW_ICON: require('../../assets/images/rightArrow_icon.png'),
    HOME_ICON:require('../../assets/images/home_icon.png'),
    SEARCH_ICON:require('../../assets/images/search_icon.png'),
    LIKE_ICON:require('../../assets/images/liked_icon.png'),
    CART_ICON:require('../../assets/images/cart_icon.png'),
    ACCOUNT_ICON:require('../../assets/images/account_icon.png'),
    NOTIFICATION_ICON:require('../../assets/images/notification_icon.png'),
    MIC_ICON:require('../../assets/images/mic_icon.png'),
    FILTER_ICON:require('../../assets/images/filter_icon.png'),
    PRODUCT_BG:require('../../assets/images/product_image.png'),
    EMPTY_NOTIFICATIONICON:require('../../assets/images/Empty_NotificationIcon.png'),
    EMPTY_BOXICON:require('../../assets/images/empty_boxIcon.png'),
    NOTFOUND_ICON:require('../../assets/images/notfound_icon.png'),
    NAVIGATION_ICON:require('../../assets/images/navigation_icon.png'),
    ORDER_ICON:require('../../assets/images/order_icon.png'),
    DETAILS_ICON:require('../../assets/images/details_icon.png'),
    ADDRESS_ICON:require('../../assets/images/address_icon.png'),
    PAYMENT_ICON:require('../../assets/images/payment_icon.png'),
    HELP_ICON:require('../../assets/images/help_icon.png'),
    QUESTIONS_ICON:require('../../assets/images/question_icon.png'),
    LOGOUT_ICON:require('../../assets/images/logout_icon.png'),
    WHATSAPP_ICON:require('../../assets/images/whatsapp_icon.png'),
    INSTA_ICON:require('../../assets/images/insta_icon.png'),
    WEB_ICON:require('../../assets/images/web_icon.png'),
    FB_ICON:require('../../assets/images/fb_icon.png'),
    TWITTER_ICON:require('../../assets/images/twitter_icon.png'),
    WARNING_ICON:require('../../assets/images/warning_icon.png'),
    SAVED_ICON:require('../../assets/images/saved_icon.png'),
    UNSAVED_ICON:require('../../assets/images/unsaved_icon.png'),
    RATING_ICON:require('../../assets/images/rating_icon.png'),
    BOX_ICON:require('../../assets/images/box_icon.png'),

};
export default images;